### ISSUE TITLE
Launch Checklist

### ISSUE THREAD

**Issue by edgrosvenor** [edgrosvenor/me#1]
# Day One Checklist
- [ ] Set up StyleCI
- [ ] Set Up ChipperCI
- [ ] Set Up Vapor Environments
- [ ] Set Up DNS

# Pre-Launch Checklist
- [ ] Remove temporary routes from routes/web.php
- [ ] Remove App\Http\Controllers\TemporaryController
